- farcy/__init__.py
It looks like the method signature [was changed](https://github.com/sigmavirus24/github3.py/commit/5695b1fadcc47bab4b56fefdb6a849bf613ae598#diff-4ca7f15885d8c65603b4b1a818bda2c4L83). This PR will have Farcy use the new signature.
> Update to use new Github3.py api for file contents

- farcy/__init__.py
Add support for PRs that add files to the repo.
> Add support for added files in PR

- farcy/__init__.py
Ended up doing two features in 1 branch:
Adds support for blacklisting files in PRs based on their paths. Example:
```bash
farcy --blacklist-path 'node_modules/*' --blacklist-path 'app/assets/vendor/*' appfolio farcy
```
Adds support for whitelisting users whose PRs Farcy has to process. Example:
```bash
farcy --limit-user balloob --limit-user bboe appfolio farcy
```
> Add support for blacklist path and whitelist user

- farcy/__init__.py
- farcy/helpers.py
- setup.py
- test/test_helpers.py
While debugging why issues couldn't be found, I cleaned up the handle_pr method. Found and fixed a bug in github3.py which changed the API, this PR updates for that new api. 
~~Should only merge after sigmavirus24/github3.py#397 has been merged.~~ Fix has been merged into github3.py
> Fixes for Github3.py api changes

- farcy/__init__.py
* Add user to event debug message
* Remove sleep debug message
* Use debug log for items that do not involve processing
* Fix pluralization issue with issue count of 0.
> Improve logging.

- .travis.yml
- farcy/__init__.py
- farcy/handlers.py
- test/configs/handler_eslint.conf
- test/examples/no_issue.js
- test/examples/single_issue.js
- test/test_handlers.py
This PR adds support for ESLint and disables support for JSXHint as they overlap.
> Add support for ESLint, disable JSXHint

- farcy/__init__.py
- farcy/helpers.py
- test/test_farcy.py
- test/test_helpers.py
Move github auth to helpers as part of the config class. Move verify github auth before verify config file.
> Validate GitHub auth as part of config

- .travis.yml
- test/configs/handler_rubocop.conf
- test/examples/no_issue.rb
- test/examples/single_issue.rb
- test/test_handlers.py
Also tests the config functionality for rubocop.
> Add Rubocop tests

- farcy/__init__.py
- test/test_farcy.py
> Handle network issues in the event loop.

- farcy/__init__.py
- farcy/helpers.py
- test/test_helpers.py
Also, expand Config to take in overrides so additional calls are not necessary.
> Complete helper.py test coverage.

- README.rst
Adds a section about config files to the README
> Add configuration instructions to README

- README.rst
Some extra clarification for the Docker config.
> Update Docker documentation

- README.rst
> Add myself to copyright

- farcy/__init__.py
- farcy/helpers.py
- test/test_farcy.py
- test/test_helpers.py
Also speed up "boot" time and refactor some of `handle_pr`.
> Support processing individual pull requests.

- Dockerfile
This is a commonly used style guide. A lot of people extend from this one. Useful if we add it.
> Add eslint-config-airbnb to Dockerfile

- README.rst
> dr: fix rubocop typo

- farcy/__init__.py
- farcy/exceptions.py
- farcy/handlers.py
- farcy/objects.py
- test/examples/no_issue.py
- test/examples/single_issue.py
- test/test_handlers.py
Some Pep257 violations were cropping up in my PR, this PR fixes them.
> Fix Pep257 style violations

- .travis.yml
- Dockerfile
- farcy/handlers.py
- test/configs/handler_scsslint.conf
- test/examples/no_issue.scss
- test/examples/single_issue.scss
- test/test_handlers.py
per https://github.com/appfolio/farcy/issues/89,
Add support for css and scss linting using https://github.com/brigade/scss-lint
> Add Support for SCSS Lint

- farcy/__init__.py
forgot to add new handler to `_load_handlers`
> Actually load SCSSLint Handler

- CHANGES.md
- farcy/__init__.py
This update should resolve #84 and #86.
> Add catch-all for exceptions that could occur with events.

- farcy/__init__.py
This change should prevent crashes from such exceptions and produce some
information as to why those crashes are occuring.
> Fix #86. Handle and log UnprocessableEntity exceptions.

- CHANGES.md
- farcy/const.py
Updating CHANGES and version to reflect the bump to v1.1
> Release version 1.1

- .travis.yml
- setup.cfg
- test/helper.py
- test/test_handlers.py
Our test file was not passing pep8.
Should we include testing it to travis?
> Flake8 test fixes
