farcy/__init__.py

Fixes Python 3 support.
`dict().items` returns an iterator in Python 3. Iterators do not allow the dictionary to be modified underneath them.

Python 3 fix for reporting issues

---

farcy/__init__.py

The final result will be saved as a status on the last commit instead of a comment on the pull request.
[Example repo with commit status added](https://github.com/balloob/trigger-rubocop/pull/2)
Fixes issue #19

Save result as commit status

---

farcy/__init__.py
farcy/handlers.py

This adds a jsxhint handler for Farcy.
I don't want to merge it because it feels like a hack:
* I had to overwrite `_process` because I wanted to provide command line arguments. Duplicating code in the process.
* I had to overwrite `assert_usable` because jsxhint outputs the version string to `STDERR`.
* `version_callback` does no error checking
I wonder if I should restructure `ExtHandler` and the other handlers to allow certain pieces of code to be more easily reused or stay with the code duplication.

Add JSXHint handler

---

farcy/__init__.py
farcy/const.py
farcy/handlers.py

This pull request adds support for configuration files for your linters.
As discussed last week, Farcy will look for configuration files in the folder `~/.config/farcy/handler_{name}.conf`.

Add support for linter configuration files

---

farcy/__init__.py

Small bugfix where Farcy would not disable whitelisting users if none given.

Bugfix: disable whitelisting user feature if none given

---

farcy/__init__.py

This should prevent the following critical messages from happening:
```
2015/06/16 17:11:23 CRITICAL Unexpected file status renamed on […]
2015/06/16 17:10:47 CRITICAL Unexpected file status removed on […]
```

Add support for removed/renamed in file processing

---

farcy/__init__.py
farcy/helpers.py
test/test_farcy.py
test/test_helpers.py

GitHub adds a message to end of diffs if there was no newline at the end of a file:
```diff
@@ -0,0 +1,6 @@
+class SomeClass
+  def yo(some_unused_param)
+    # some really long comment some really long comment some really long comment some really long comment some really long comment
+    puts 'hi'
+  end
+end
\ No newline at end of file
```
This broke the `added_lines` method. I fixed this and added a test for this case. I also moved the added_lines method to the helpers file.

No longer fail when parsing patch with no newline at end msg

---

farcy/__init__.py
test/test_farcy.py

Tempfile produces files with odd names and can result in some warnings. This
commit makes a temporary directory to place files with the same name in prior
to processing.
This PR should resolve #32.

Create temporary directory to put saved files in.

---

farcy/__init__.py

The name of `pfile.filename` is misleading as it also includes the full path of the file relative to the repository root. `open()` will raise a `FileNotFoundError` if we target a directory that does not exist.
This PR will only use the filename and strip out the path.

No longer crash when handling files in folders

---

farcy/__init__.py

This will limit the total number of comments that Farcy will add to a single PR, taking existing comments by Farcy into consideration. Currently defaulted to 128.
Includes an extra commit because branch is based on PR #39.
This PR fixes #35.

Limit comments

---

farcy/__init__.py
farcy/helpers.py
test/test_farcy.py
test/test_helpers.py

Also:
* allow each user argument to be a comma separated list
* normalize user each argument by doing lowercase comparision
* return a user set rather than a list

Add short arguments for `limit-user` and `comments-per-pr`.

---

farcy/__init__.py

This will add a pending commit status when Farcy is handling a PR so the user can see Farcy is running.
In the future we will probably want to have our event handlers set up a pending state right away. But to do this we would have to have to convert to a process queue instead of handling PRs synchronosouly  when events come in.

Added pending commit status on start handle_pr

---

farcy/__init__.py
farcy/helpers.py
test/test_farcy.py
test/test_helpers.py

This is an initial version to add support for configuring Farcy via configuration files. It supports a structure similar to [praw](http://praw.readthedocs.org/en/latest/pages/configuration_files.html): a default configuration section and a section per repository.
- Configuration priority is: command line arguments > repo specific section > default section. They overwrite one another, they will not be merged.
- It will look for a configuration file at `~/.config/farcy/farcy.conf`.
- The default section supports 1 extra parameter: `repository`. This will be used if no repository given as command line argument.
- Debug expects a true-ish value: `true` or `1`
Example:
```conf
[default]
repository: appfolio/farcy
limit_users: balloob
exclude_paths: node_modules, vendor, db
[appfolio/farcy] …
```

Initial version config file support

---

farcy/__init__.py

Prints active handlers on launch. Right now prints a warning if no active found. Since Farcy is useless without, should we just quit?

Output active handlers on start

---

Dockerfile
README.rst

This adds support for Docker.
Right now, if the config does not point at a repo, it will never ask for GitHub credentials. We should probably switch the check for no repository with GitHub credentials. Also we should add a readme section about configuration files

Initial Docker support

---

farcy/__init__.py
farcy/objects.py
setup.py
test/helper.py
test/test_objects.py

Hidden comments are comments that github considers to be on "outdated
diffs". In the event that farcy has reached its self-imposed comment limit, it
would no longer make new comments making it impossible from the pull request
view to receive feedback on new issues. Because those comments are hidden on
page load, ignoring them in the comment count _should_ avoid the breaking the
pull request view (the reason why #35 was filed and subsequently resolved).
In the event we break pull request views again, we can use the information
about hidden comments to delete as many as needed.
Resolve #78.

Ignore "hidden" comments.

---

.travis.yml

This will make Travis report the final status as soon as no other builds can have any impact on the final status. So if 1 build fails it will already report that the overall status is failed, if there are only jobs left that we allow failures of, it will mark the PR as a success.
[More info in their blog post](https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/)

Add fast_finish to travis.yml

---

CHANGES.md
farcy/__init__.py

This fix resolves #87, and a 502 error I received in the same section of code.

Handle github3.py ServerError around event_loop.

---

CHANGES.md
farcy/handlers.py
test/examples/linting_exception.scss
test/test_handlers.py

- Adds a useful error message when SCSS-Lint throws an exception while linting. Closes #99
- Also, adds SCSS-Lint to the Unreleased section of `CHANGES.md`

Throw Useful SCSS-Lint Exception

---

farcy/__init__.py
farcy/objects.py

One of the Flake8 dependencies became more strict. This PR fixes the new issues so CI passes.
```
farcy/__init__.py:307:34: W503 line break before binary operator
farcy/objects.py:51:23: W503 line break before binary operator
farcy/objects.py:259:5: E731 do not assign a lambda expression, use a def
farcy/objects.py:260:5: E731 do not assign a lambda expression, use a def
farcy/objects.py:261:5: E731 do not assign a lambda expression, use a def
```

Fix Flake8 issues

---

farcy/handlers.py
test/examples/invalid_syntax.js
test/test_handlers.py

ESLint will not have a ruleId as part of the message when it encounters invalid syntax. With this PR, the ESLint handler will no longer fail with an exception of being unable to find key 'ruleId' but print the correct error message.

ESLint to handle invalid JS syntax
